version: "3"
services:
  api:
    build: ./therush-api
    volumes:
      - ./therush-api:/app
    ports:
      - 5000:3000
    command: bash -c "rake db:create && rake db:migrate && rake db:migrate RAILS_ENV=test && rails s -b '0.0.0.0'"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: therush-api_development
    ports:
      - 6432:5432
  client:
    build: ./therush-client
    volumes:
      - ./therush-client:/app
      - /app/node_modules
    ports:
      - 8888:3000
    command: yarn start
